[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/webhook/whatsapp"
  to = "/.netlify/functions/webhook-whatsapp"
  status = 200

[[redirects]]
  from = "/webhooks/whatsapp"
  to = "/.netlify/functions/webhooks-whatsapp"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200